# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23d44908e05b3a58171a2b0058eeef0ee9c9a61c8d30ad3d5756e740246105df06df07922d73928b7348927f5f0e0cb2816a19368a3840e4e8cee06ed2539d38

test:
  secret_key_base: 9302930e6aa3e90d67a79f3bd93c90fc75398255f3cb30f5725e1e5ac30f81d46fe44f5714d97ec3ca4ed3740ab08bb7b1f029d828903bec4415766b4720876a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
